spring.application.name=CURRENCYCONVERTER

spring.datasource.url=jdbc:mysql://localhost:3306/prodfeatures
spring.datasource.username=root
spring.datasource.password=Sourav6113

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name = user
server.port = 8080

freecurrency.api.key=fca_live_vs2uX4JxlWO1DKXfeCR33hSdxRcMMi5ZOgynM6ei
freecurrency.api.url=v1/latest
